### ISSUE TITLE
Remote reprogrammer needs Python 3 tweaks

### ISSUE THREAD

**Issue by jkelley** [mkauer/py7slib#3]
The remote WR-LEN firmware updater `spiflash_update.py` needs some Py3 tweaks -- a few things I found:

- `periph/ipc_spiflash.py` has some `Exception, e` (there are a few more, in say `tools/commentsRemover.py`)
- `periph/ipc_spiflash.py` has a `print self.SR_to_str(new_SR)`
- the mcs decoder then ran into this:
```
 File "/home/pdaq/wr-len/py7slib/bridges/ethbone.py", line 503, in dataToByteArray
    hex_line=line.decode("hex")
LookupError: 'hex' is not a text encoding; use codecs.decode() to handle arbitrary codecs
```
I didn't want to try this on the field WR-LEN so was going to suggest we test a fixed version at SPTS first.

**Comment by mkauer** [comment]
@jkelley 
Do you want me to work on this? How should I go about testing? I don't have experience updating the flash. Can you point me at the new firmware file?
